version: "3.2"

services:
  chord-node-1:
    image: jmederosalvarado/chord
    container_name: chord-node-1
    command: /bin/sh -c "echo 'export IP=10.0.0.2' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.2
    expose:
      - 5000
  chord-node-2:
    image: jmederosalvarado/chord
    container_name: chord-node-2
    command: /bin/sh -c "echo 'export IP=10.0.0.3' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.3
    expose:
      - 5000
  chord-node-3:
    image: jmederosalvarado/chord
    container_name: chord-node-3
    command: /bin/sh -c "echo 'export IP=10.0.0.4' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.4
    expose:
      - 5000
  chord-node-4:
    image: jmederosalvarado/chord
    container_name: chord-node-4
    command: /bin/sh -c "echo 'export IP=10.0.0.5' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.5
    expose:
      - 5000
  chord-node-5:
    image: jmederosalvarado/chord
    container_name: chord-node-5
    command: /bin/sh -c "echo 'export IP=10.0.0.6' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.6
    expose:
      - 5000
  chord-node-6:
    image: jmederosalvarado/chord
    container_name: chord-node-6
    command: /bin/sh -c "echo 'export IP=10.0.0.7' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.7
    expose:
      - 5000
  chord-node-7:
    image: jmederosalvarado/chord
    container_name: chord-node-7
    command: /bin/sh -c "echo 'export IP=10.0.0.8' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.8
    expose:
      - 5000
  chord-node-8:
    image: jmederosalvarado/chord
    container_name: chord-node-8
    command: /bin/sh -c "echo 'export IP=10.0.0.9' >> ~/.bashrc && while sleep 1000; do :; done"
    volumes:
      - .:/chord
    networks:
      default:
        ipv4_address: 10.0.0.9
    expose:
      - 5000

networks:
  default:
    external: true
    name: chord-net
